### ISSUE TITLE
tdm64-gcc-9.2.0.exe install error (Windows 7, 64bit)

### ISSUE THREAD

**Issue by diegoefe** [jmeubank/tdm-gcc#24] opened 2020-08-30 12:04 UTC
The installation did not started because, it seems, the net-manifest.txt cannot be found in:
[https://jmeubank.github.io/tdm-gcc/net-manifest.txt](https://jmeubank.github.io/tdm-gcc/net-manifest.txt)

![tdm-install-error](https://user-images.githubusercontent.com/1447920/91658540-64333a80-ea9f-11ea-9c93-c995fdd819f2.png)
![tdm-install-error2](https://user-images.githubusercontent.com/1447920/91658541-65fcfe00-ea9f-11ea-9f99-7a52f3b0f874.png)

**Comment by jmeubank** [comment] 2020-08-30 17:16
Might be a duplicate of #5. If so, a new download mechanism will be needed in the installer; but meanwhile you can try the same troubleshooting steps from that issue.

**Comment by jmeubank** [comment] 2020-09-18 15:18
Will close as duplicate shortly if no further information provided.

**Closed** 2020-09-21 22:50 UTC
Labels: duplicate
